version: "3"
services: 
    web:
        build: .
        command : python manage.py runserver 0:8000
        volumes:
            - .:/code
        depends_on: 
            - db

    db:
        image: mariadb
        ports:
            - "3306:3306"
